### ISSUE TITLE
use --graph parameter in git log

### ISSUE THREAD

**Issue by lobneroO** [paopaol/telescope-git-diffs.nvim#5]
Is there any chance of supporting the `--graph` parameter for the telescope picker?
The display sort of works if you add it as is right now, but the DiffView functionality doesn't work anymore, neither does the diff preview.

![image](https://github.com/user-attachments/assets/d732c71b-6a4f-44e0-abda-fcd4759aeb45)

I find it a bit easier to select the correct commit if you see the actual branching visually. Though I admit, I don't have an idea of how it would like with "many" parallel branches.

**Comment by paopaol** [comment]
Thanks for your suggestion, maybe I can give it a try

**Comment by ProfessorMinius** [comment]
All you need to do is isolate the commit hash so that you could run the diffs. I suppose you could accomplish that with a simple regex.
